create table reply (id int8 generated by default as identity, body TEXT, date timestamp, topic_id int8, primary key (id));
create table topic (id int8 generated by default as identity, body TEXT, date timestamp, title varchar(255), primary key (id));
alter table if exists reply add constraint FKgf3tac9fa0n9vf62c7eh5eb4y foreign key (topic_id) references topic;
